# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    
    - task: oc-cmd@3
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'OpenShift'
        version: '4.17'
        cmd: 'oc project weatherforecast'
    
    - task: oc-cmd@3
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'OpenShift cluster'
        version: '4.17'
        cmd: 'oc project myapp'
      displayName: Switch to myapp project

    - task: oc-cmd@3
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'OpenShift cluster'
        version: '4.17'
        cmd: 'oc new-app https://github.com/Bashayr29/simple-app.git'
        ignoreFlag: true
        
    - task: oc-cmd@3
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'OpenShift cluster'
        version: '4.17'
        cmd: 'oc expose svc simple-app'
        ignoreFlag: true
      displayName: Create route

    - task: oc-cmd@3
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'OpenShift cluster'
        version: '4.17'
        cmd: 'oc start-build simple-app --follow'
      displayName: Start new build

    - task: oc-cmd@3
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'OpenShift cluster'
        version: '4.17'
        cmd: 'oc status'
         