# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: oc-setup@3
      displayName: 'OC Setup'
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'OpenShift'

    - task: oc-cmd@3
      displayName: 'OC Version'
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'OpenShift'
        cmd: 'oc version'

    - task: oc-cmd@3
      displayName: 'OC Switch Project'
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'OpenShift'
        cmd: 'oc project christophercrawford-dev'   
    
    - task: oc-cmd@3
      displayName: 'OC New App'
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'OpenShift'
        cmd: 'oc new-app $(Build.SourcesDirectory) --allow-missing-images=true --name="podmansample"'