# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: oc-setup@3
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'OpenShift'

    - task: oc-cmd@3
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'OpenShift'
        cmd: 'oc version'

    - task: oc-cmd@3
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'OpenShift'
        cmd: 'oc project PodmanSample'   
    
    - task: oc-cmd@3
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'OpenShift'
        cmd: 'oc new-app https://github.com/vcnws/PodmanSample.git'